export const SET_DATA_CANDIDATES = 'SET_DATA_CANDIDATES';
export const SET_DATA_QUESTIONS = 'SET_DATA_QUESTIONS';
export const SET_DATA_APPLICATION = 'SET_DATA_APPLICATION';
export const CLEAR_DATA_APPLICATION = 'CLEAR_DATA_APPLICATION';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const SERVICE_DOWN = 'SERVICE_DOWN';